
// Sample data for demonstration purposes

export const recentMatchesData = [
  {
    id: 1,
    opponent: 'FC Barcelona',
    result: 'Win',
    score: '3-1',
    possession: 58,
    shots: 14,
    shotsOnTarget: 8,
    passes: 432,
    passAccuracy: 87,
    date: '2023-05-15',
  },
  {
    id: 2,
    opponent: 'Real Madrid',
    result: 'Loss',
    score: '1-2',
    possession: 45,
    shots: 9,
    shotsOnTarget: 3,
    passes: 389,
    passAccuracy: 79,
    date: '2023-05-08',
  },
  {
    id: 3,
    opponent: 'Bayern Munich',
    result: 'Draw',
    score: '2-2',
    possession: 51,
    shots: 12,
    shotsOnTarget: 6,
    passes: 401,
    passAccuracy: 82,
    date: '2023-05-01',
  },
  {
    id: 4,
    opponent: 'Liverpool FC',
    result: 'Win',
    score: '2-0',
    possession: 54,
    shots: 11,
    shotsOnTarget: 7,
    passes: 415,
    passAccuracy: 85,
    date: '2023-04-24',
  },
  {
    id: 5,
    opponent: 'Manchester City',
    result: 'Loss',
    score: '0-3',
    possession: 40,
    shots: 8,
    shotsOnTarget: 2,
    passes: 375,
    passAccuracy: 76,
    date: '2023-04-17',
  },
];

export const playerStatsData = [
  {
    id: 1,
    name: 'Alex Johnson',
    position: 'ST',
    matches: 25,
    goals: 18,
    assists: 7,
    rating: 8.4,
    shotsOnTarget: 42,
    passAccuracy: 86,
    image: 'https://images.unsplash.com/photo-1531891570158-e71b35a485bc?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=80',
  },
  {
    id: 2,
    name: 'Marcus Williams',
    position: 'CAM',
    matches: 24,
    goals: 12,
    assists: 15,
    rating: 8.7,
    shotsOnTarget: 38,
    passAccuracy: 91,
    image: 'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=80',
  },
  {
    id: 3,
    name: 'David Lee',
    position: 'CM',
    matches: 25,
    goals: 5,
    assists: 9,
    rating: 7.9,
    shotsOnTarget: 21,
    passAccuracy: 88,
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=80',
  },
  {
    id: 4,
    name: 'Carlos Rodriguez',
    position: 'LB',
    matches: 23,
    goals: 1,
    assists: 6,
    rating: 7.6,
    shotsOnTarget: 8,
    passAccuracy: 83,
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=80',
  },
  {
    id: 5,
    name: 'Michael Chen',
    position: 'CB',
    matches: 25,
    goals: 2,
    assists: 1,
    rating: 7.8,
    shotsOnTarget: 5,
    passAccuracy: 80,
    image: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=80',
  },
];

export const performanceTrendsData = [
  { name: 'Match 1', rating: 7.1, goals: 1, assists: 0 },
  { name: 'Match 2', rating: 7.4, goals: 1, assists: 1 },
  { name: 'Match 3', rating: 6.9, goals: 0, assists: 0 },
  { name: 'Match 4', rating: 8.2, goals: 2, assists: 1 },
  { name: 'Match 5', rating: 7.8, goals: 1, assists: 2 },
  { name: 'Match 6', rating: 8.5, goals: 2, assists: 1 },
  { name: 'Match 7', rating: 7.6, goals: 0, assists: 1 },
  { name: 'Match 8', rating: 8.0, goals: 1, assists: 0 },
  { name: 'Match 9', rating: 8.7, goals: 3, assists: 0 },
  { name: 'Match 10', rating: 8.3, goals: 1, assists: 2 },
];

export const teamStatsByPosition = [
  { name: 'GK', rating: 7.5, goals: 0, assists: 0, cleanSheets: 8 },
  { name: 'DEF', rating: 7.8, goals: 5, assists: 7, cleanSheets: 8 },
  { name: 'MID', rating: 8.1, goals: 18, assists: 22, cleanSheets: 0 },
  { name: 'FWD', rating: 8.3, goals: 35, assists: 14, cleanSheets: 0 },
];

export const teamResultsData = [
  { name: 'Wins', value: 15 },
  { name: 'Draws', value: 7 },
  { name: 'Losses', value: 3 },
];

export const possessionByMatchData = [
  { name: 'Match 1', possession: 58, opponentPossession: 42 },
  { name: 'Match 2', possession: 45, opponentPossession: 55 },
  { name: 'Match 3', possession: 51, opponentPossession: 49 },
  { name: 'Match 4', possession: 54, opponentPossession: 46 },
  { name: 'Match 5', possession: 40, opponentPossession: 60 },
  { name: 'Match 6', possession: 62, opponentPossession: 38 },
  { name: 'Match 7', possession: 57, opponentPossession: 43 },
  { name: 'Match 8', possession: 49, opponentPossession: 51 },
];

export const seasonProgressionData = [
  { name: 'Week 1', points: 3, position: 8 },
  { name: 'Week 2', points: 6, position: 6 },
  { name: 'Week 3', points: 7, position: 6 },
  { name: 'Week 4', points: 10, position: 4 },
  { name: 'Week 5', points: 10, position: 5 },
  { name: 'Week 6', points: 13, position: 3 },
  { name: 'Week 7', points: 16, position: 3 },
  { name: 'Week 8', points: 17, position: 3 },
  { name: 'Week 9', points: 20, position: 2 },
  { name: 'Week 10', points: 23, position: 2 },
  { name: 'Week 11', points: 26, position: 1 },
  { name: 'Week 12', points: 27, position: 2 },
  { name: 'Week 13', points: 30, position: 2 },
  { name: 'Week 14', points: 33, position: 1 },
  { name: 'Week 15', points: 36, position: 1 },
];
